-- ==============================================================================
-- Bubbles Play & Learn Co. - Supabase Database Schema
-- Table: orders
-- Description: Stores customer orders placed through the website checkout flow
-- ==============================================================================

-- 1. Create the orders table
create table if not exists public.orders (
  -- Primary order identifier (UUID generated by PostgreSQL)
  id uuid primary key default gen_random_uuid(),

  -- Human-readable order reference number (e.g. BUB-123456)
  order_number text,

  -- Order timestamp with timezone
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Customer Information
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_address text not null,
  district text not null,
  delivery_notes text,

  -- Order details
  -- items stores an array of ordered products: [{id, title, price, quantity, imageSrc, isCustomBox, customData}]
  items jsonb not null default '[]'::jsonb,
  
  -- Financial totals
  total_amount numeric(12, 2) not null,
  payment_method text not null, -- 'cod' (Cash on Delivery), 'bank' (Bank Transfer), 'card' (Card/Koko)

  -- Order Lifecycle Status
  -- Values: 'Pending', 'Packed', 'Handed to Courier', 'Delivered', 'Cancelled'
  status text not null default 'Pending'
);

-- 2. Add documentation comments
comment on table public.orders is 'Customer orders placed on Bubbles Play & Learn website';
comment on column public.orders.items is 'JSONB array of ordered items, quantities, and pricing breakdown';
comment on column public.orders.status is 'Order fulfillment status: Pending, Packed, Handed to Courier, Delivered, Cancelled';

-- 3. Create indexes for fast querying in Admin Dashboard
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_customer_phone_idx on public.orders (customer_phone);
create index if not exists orders_district_idx on public.orders (district);

-- 4. Enable Row Level Security (RLS)
alter table public.orders enable row level security;

-- 5. Row Level Security Policies

-- Policy A: Anyone (public / anonymous customers) can insert new orders during checkout
drop policy if exists "Allow public to place orders" on public.orders;
create policy "Allow public to place orders"
  on public.orders
  for insert
  to anon, authenticated
  with check (true);

-- Policy B: Authenticated administrators can read all orders in the Admin Dashboard
drop policy if exists "Allow authenticated admins to read orders" on public.orders;
create policy "Allow authenticated admins to read orders"
  on public.orders
  for select
  to authenticated
  using (true);

-- Policy C: Authenticated administrators can update order status (e.g. Pending -> Packed -> Delivered)
drop policy if exists "Allow authenticated admins to update orders" on public.orders;
create policy "Allow authenticated admins to update orders"
  on public.orders
  for update
  to authenticated
  using (true)
  with check (true);

-- Policy D: Optional - Allow authenticated administrators to delete orders if needed
drop policy if exists "Allow authenticated admins to delete orders" on public.orders;
create policy "Allow authenticated admins to delete orders"
  on public.orders
  for delete
  to authenticated
  using (true);

-- 6. Enable Realtime updates for live order notifications in Admin Dashboard
-- (Run this if publication exists in your Supabase project)
do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;
