import fs from 'fs';

const items = [
  {
    id: 'toddler-01',
    title: 'Color Classic Block Stacking Game Premium Wooden Board Game Tumbling Tower Building Blocks Set for Children',
    category: 'wooden-local',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1500.51,
    originalPrice: 1850,
    rating: 4.8,
    reviewsCount: 26,
    imageSrc: 'assets/products/extracted_1_2/img_1.jpg',
    imageType: 'wooden-blocks',
    material: 'Natural Beechwood & Non-toxic Water-based Paint',
    madeIn: 'Child-Safe Certified',
    inStock: true,
    tag: 'Balance & Motor Skills',
    description: 'Colorful classic wooden stacking blocks and tumbling tower game designed to build toddler spatial balance, hand-eye coordination, and color recognition.',
    milestones: ['Fine motor grip', 'Spatial balance', 'Color recognition']
  },
  {
    id: 'toddler-02',
    title: 'Kids Toys Educational Learning Xylophone Keys Percussion Musical Instrument Music Book Preschool Kindergarten Educational Toys',
    category: 'sensory',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 5186.95,
    originalPrice: 5900,
    rating: 4.9,
    reviewsCount: 38,
    imageSrc: 'assets/products/extracted_1_2/img_2.jpg',
    imageType: 'xylophone',
    material: 'Smooth Polished Wood Base with Multi-Color Metal Tuning Keys',
    madeIn: 'Safety Certified',
    inStock: true,
    tag: 'Music & Auditory',
    description: 'Educational learning xylophone with rainbow keys, percussion mallets, and musical learning book to foster auditory exploration, rhythm sensitivity, and fine motor grip.',
    milestones: ['Auditory perception', 'Rhythm coordination', 'Bilateral hand movement']
  },
  {
    id: 'toddler-03',
    title: 'Animal Cognition Blocks Educational Color Sorting Fidget Sensory Plastic Learning Toy for Baby Girl 1-3 Years Toys',
    category: 'sensory',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 2945.45,
    originalPrice: 3500,
    rating: 4.8,
    reviewsCount: 22,
    imageSrc: 'assets/products/extracted_1_2/img_3.jpg',
    imageType: 'wooden-train',
    material: 'BPA-Free Food Grade ABS Plastic with Tactile Fidget Elements',
    madeIn: 'Certified Child-Safe',
    inStock: true,
    tag: 'Color Sorting & Train',
    description: 'Educational animal cognition blocks and colorful sorting train toy fostering sensory color matching, tactile fidget exploration, and early imaginative storytelling.',
    milestones: ['Animal cognition', 'Color sorting', 'Fine motor tactile play']
  },
  {
    id: 'toddler-04',
    title: 'Montessori Wooden Color & Number Matching Board Educational Toy for Kids Preschool Learning Teaching Aid Z12070F',
    category: 'montessori',
    secondaryCategory: 'steam-math',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1796.91,
    originalPrice: 2200,
    rating: 4.9,
    reviewsCount: 45,
    imageSrc: 'assets/products/extracted_1_2/img_4.jpg',
    imageType: 'cards-counters',
    material: 'Natural Solid Basswood & Non-toxic Food Grade Lacquer',
    madeIn: 'Montessori Certified',
    inStock: true,
    tag: 'Math & Matching',
    description: 'Montessori wooden color and number matching board featuring vibrant colored pegs and counting slots to develop mathematical thinking, number recognition, and fine motor precision.',
    milestones: ['Number recognition', 'Color matching', 'Pincer grasp development']
  },
  {
    id: 'toddler-05',
    title: '7pcs/set Fun Montessori Educational Toys for Kids 1-2 Years Old Early Intellectual Development Wooden Music Hand Knock Toys',
    category: 'montessori',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1600,
    originalPrice: 2100,
    rating: 4.9,
    reviewsCount: 52,
    imageSrc: 'assets/products/extracted_1_2/img_5.jpg',
    imageType: 'busy-board',
    material: 'Sustainably Sourced Beechwood with Smooth Rounded Corners',
    madeIn: 'Montessori Certified',
    inStock: true,
    tag: '7-in-1 Value Set',
    description: 'Comprehensive 7-piece Montessori early intellectual development wooden toy set with rainbow xylophone, clock, shape puzzle, and hand-knock rhythm instruments.',
    milestones: ['Sensory exploration', 'Hand-eye coordination', 'Intellectual discovery']
  },
  {
    id: 'toddler-06',
    title: 'Preschool Math Learning Stick Counting Toy Wooden Number Peg Board for Kids Z12174E',
    category: 'steam-math',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1852.48,
    originalPrice: 2300,
    rating: 4.8,
    reviewsCount: 31,
    imageSrc: 'assets/products/extracted_1_2/img_6.jpg',
    imageType: 'cards-counters',
    material: 'Solid Wood Board with Colored Counting Rods',
    madeIn: 'Educational Standard',
    inStock: true,
    tag: 'Early Math Counting',
    description: 'Wooden number peg board with counting sticks and mathematical operation symbols, encouraging hands-on quantity visualization and early numeracy.',
    milestones: ['Counting fundamentals', 'Quantity perception', 'Fine motor manipulation']
  },
  {
    id: 'toddler-07',
    title: '8 Pcs Geometry Shape Learning Blocks',
    category: 'montessori',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 8250,
    originalPrice: 9500,
    rating: 5.0,
    reviewsCount: 19,
    imageSrc: 'assets/products/extracted_1_2/img_7.jpg',
    imageType: 'wooden-blocks',
    material: 'Premium Hardwood with Certified Organic Vegetable Dyes',
    madeIn: 'Handcrafted Premium',
    inStock: true,
    tag: 'Geometric Sorting',
    description: 'Premium 8-piece solid wooden geometric shape learning blocks set with stacking column boards for sorting, height comparison, and spatial geometry.',
    milestones: ['Spatial reasoning', 'Shape differentiation', 'Constructive stacking']
  },
  {
    id: 'toddler-08',
    title: 'Abacus – 10 Grade – Wooden Toys',
    category: 'steam-math',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y', '3-4y'],
    price: 3600,
    originalPrice: 4200,
    rating: 4.9,
    reviewsCount: 44,
    imageSrc: 'assets/products/extracted_1_2/img_8.jpg',
    imageType: 'cards-counters',
    material: 'Natural Pine Wood Frame & Polished Wooden Counting Beads',
    madeIn: 'Handcrafted',
    inStock: true,
    tag: 'Classic Abacus',
    description: '10-row colorful wooden abacus calculator with smooth slide beads for tactile counting, addition practice, and color grading exploration.',
    milestones: ['Number visualization', 'Sliding fine motor grip', 'Tactile math logic']
  },
  {
    id: 'toddler-09',
    title: 'Bead Maze Activity',
    category: 'arts-fine-motor',
    secondaryCategory: 'sensory',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 3900,
    originalPrice: 4500,
    rating: 4.8,
    reviewsCount: 29,
    imageSrc: 'assets/products/extracted_1_2/img_9.jpg',
    imageType: 'busy-board',
    material: 'Solid Wood Base with Smooth Plastic-Coated Wire Tracks',
    madeIn: 'Child-Safe Certified',
    inStock: true,
    tag: 'Fine Motor Track',
    description: 'Classic wooden bead maze activity center featuring multi-track looping wires, colorful fruit and sphere beads, and counting beads on a solid wood base.',
    milestones: ['3D tracking coordination', 'Wrist articulation', 'Problem solving']
  },
  {
    id: 'toddler-10',
    title: 'Wooden Number Counting Board Bead Sorting Spoon Tweezers Fine Motor Early Math Toddler Preschool Toys for Children',
    category: 'steam-math',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1207.82,
    originalPrice: 1650,
    rating: 4.9,
    reviewsCount: 57,
    imageSrc: 'assets/products/extracted_1_2/img_10.jpg',
    imageType: 'cards-counters',
    material: 'Basswood Pegboard, Food-Grade Silicone Bowls & Wood Tweezers',
    madeIn: 'Montessori Certified',
    inStock: true,
    tag: 'Tweezer & Bead Math',
    description: 'Montessori wooden counting board with rainbow silicone sorting cups, wooden beads, spoon, and tweezers designed for pincer grasp training and math logic.',
    milestones: ['Tweezer pincer grip', 'Color classification', 'Mathematical grouping']
  },
  {
    id: 'toddler-11',
    title: 'Busy Board Montessori Educational Toys Led Light Switch Diy Wooden Hands-on Screw Nut Early Educational Toys',
    category: 'montessori',
    secondaryCategory: 'sensory',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y', '3-4y'],
    price: 3630.87,
    originalPrice: 4300,
    rating: 5.0,
    reviewsCount: 68,
    imageSrc: 'assets/products/extracted_1_2/img_11.jpg',
    imageType: 'busy-board',
    material: 'Natural Solid Wood, LED Light Components & Metal Switch Hardware',
    madeIn: 'Safety Certified',
    inStock: true,
    tag: 'LED Busy Board',
    description: 'Interactive wooden sensory busy board featuring multi-colored LED push buttons, toggle switches, key lock, and screw nut mechanics to satisfy toddler curiosity and cause-and-effect understanding.',
    milestones: ['Cause and effect', 'Finger strength & dexterity', 'Practical life mechanics']
  },
  {
    id: 'toddler-12',
    title: 'Wooden Activity Table Bead Maze Counting Roller Clock Gear Fine Motor Early Math Learning Toddler Toys for Children',
    category: 'wooden-local',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 5560.81,
    originalPrice: 6800,
    rating: 4.9,
    reviewsCount: 35,
    imageSrc: 'assets/products/extracted_1_2/img_12.jpg',
    imageType: 'busy-board',
    material: 'Solid Wood Legs & Engineered Eco-MDF Activity Surface',
    madeIn: 'Safety Tested',
    inStock: true,
    tag: 'Multi-Activity Table',
    description: 'All-in-one standing wooden activity play table with bead maze wire tracks, counting roller, clock, and interlocking gears for standing balance and multi-sensory discovery.',
    milestones: ['Supported standing balance', 'Bimanual coordination', 'Gear cause-and-effect']
  },
  {
    id: 'toddler-13',
    title: 'Animal Cause and Effect Sensory Toy Musical Pop-up Light Game for Baby Twist Press Hide and Seek Toy',
    category: 'sensory',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1800,
    originalPrice: 2250,
    rating: 4.8,
    reviewsCount: 42,
    imageSrc: 'assets/products/extracted_1_2/img_13.jpg',
    imageType: 'sensory-pop',
    material: 'Smooth Shatterproof ABS with Gentle Melody Audio',
    madeIn: 'Certified Child-Safe',
    inStock: true,
    tag: 'Pop-Up Cause & Effect',
    description: 'Pop-up hide-and-seek interactive sensory game featuring twist, slide, switch, and press mechanisms that reward toddler fine motor action with cute animal reveal and lights.',
    milestones: ['Twist & press motor actions', 'Object permanence reward', 'Auditory cues']
  },
  {
    id: 'toddler-14',
    title: 'Interactive Toddler Sound Book 108 Words Talking Learning Toy Electronic Educational Audio ABC Book for Kids Early Education',
    category: 'language',
    secondaryCategory: 'sensory',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 5631.54,
    originalPrice: 6500,
    rating: 4.9,
    reviewsCount: 51,
    imageSrc: 'assets/products/extracted_1_2/img_14.jpg',
    imageType: 'language-sandpaper',
    material: 'Durable Waterproof Laminated Board with Electronic Sound Module',
    madeIn: 'CE/CPC Certified',
    inStock: true,
    tag: 'Talking 108 Words Book',
    description: 'Talking electronic audio word book with 108 everyday vocabulary words, sound buttons, phonics, and clear pronunciation to accelerate toddler speech and bilingual cognitive development.',
    milestones: ['Early speech development', 'Vocabulary acquisition', 'Auditory-visual association']
  },
  {
    id: 'toddler-15',
    title: 'Wooden Baby Walker Geometric Building Blocks Mini Supermarket Shopping Cart Toys',
    category: 'wooden-local',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 4075.46,
    originalPrice: 4950,
    rating: 4.8,
    reviewsCount: 39,
    imageSrc: 'assets/products/extracted_1_2/img_15.jpg',
    imageType: 'wooden-walker',
    material: 'Natural Beechwood with Rubber Trimmed Silent Wheels',
    madeIn: 'Safety Tested',
    inStock: true,
    tag: 'Walker & Cart',
    description: '2-in-1 push-along wooden baby walker and mini supermarket shopping cart loaded with geometric blocks for early walking balance, imaginative roleplay, and block construction.',
    milestones: ['Gross motor walking stability', 'Imaginative pretend play', 'Weight balance']
  },
  {
    id: 'toddler-16',
    title: 'Wooden Frame Baby Walkers Lightweight Learning Multi-Functional Toys for Kids Boys Girls',
    category: 'wooden-local',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 6554,
    originalPrice: 7800,
    rating: 4.9,
    reviewsCount: 33,
    imageSrc: 'assets/products/extracted_1_2/img_16.jpg',
    imageType: 'wooden-walker',
    material: 'Sturdy Natural Wood Frame, Water-based Paint & Rubber Ring Wheels',
    madeIn: 'Handcrafted Quality',
    inStock: true,
    tag: 'Activity Walker Center',
    description: 'Sturdy natural wood frame push walker featuring a front activity center with shape sorters, musical xylophone, bead maze, and non-slip rubberized wheels for confident first steps.',
    milestones: ['Independent walking confidence', 'Multifaceted sensory exploration', 'Spatial awareness']
  },
  {
    id: 'toddler-17',
    title: 'Six-Sided Plastic Busy House Multifunctional Infant Toy Gift 0-2 Year Olds Fine MotorEarly Education Toy',
    category: 'sensory',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '0-1y'],
    price: 4834.98,
    originalPrice: 5600,
    rating: 4.8,
    reviewsCount: 47,
    imageSrc: 'assets/products/extracted_1_2/img_17.jpg',
    imageType: 'busy-board',
    material: 'Eco-friendly ABS Plastic with Rounded Anti-Drop Corners',
    madeIn: 'Child-Safe Certified',
    inStock: true,
    tag: '6-Sided Busy House',
    description: '6-sided multi-activity discovery house equipped with rotating gears, musical piano, door key, shape sorter, and steering wheel for rich fine-motor engagement.',
    milestones: ['Fine motor dexterity', 'Multi-mechanism discovery', 'Sensory problem solving']
  },
  {
    id: 'toddler-18',
    title: 'Portable Felt Montessori Sensory Activity Board Toddler Learning Educational Toy Travel Quiet Book Preschool Skill Training',
    category: 'montessori',
    secondaryCategory: 'sensory',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 3330.76,
    originalPrice: 3950,
    rating: 4.9,
    reviewsCount: 64,
    imageSrc: 'assets/products/extracted_1_2/img_18.jpg',
    imageType: 'busy-board',
    material: 'Soft Flexible Wool Felt with Reinforced Snaps & Zippers',
    madeIn: 'Montessori Standard',
    inStock: true,
    tag: 'Felt Travel Board',
    description: 'Foldable lightweight felt Montessori busy board handbag with real zippers, shoelaces, buckles, clock hands, and button clasps to foster practical life skills and self-dressing mastery.',
    milestones: ['Self-dressing life skills', 'Pincer pinch and pull', 'Quiet travel concentration']
  },
  {
    id: 'toddler-19',
    title: 'Doodle Mini Magnetic Board Stand Drawing Toys Dry Erase Books Children Easel Magic Foldable Hot Sale Kids Painting Writing White',
    category: 'arts-fine-motor',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y', '3-4y'],
    price: 5372.20,
    originalPrice: 6400,
    rating: 4.9,
    reviewsCount: 28,
    imageSrc: 'assets/products/extracted_1_2/img_19.jpg',
    imageType: 'busy-board',
    material: 'Non-toxic ABS & Magnetic Whiteboard Surface',
    madeIn: 'Certified Safe',
    inStock: true,
    tag: 'Foldable Doodle Easel',
    description: 'Foldable mini standing double-sided magnetic easel and whiteboard for toddler mark-making, dry-erase doodle drawing, and magnet shape play without mess.',
    milestones: ['Pre-writing grip', 'Creative expression', 'Hand dominance development']
  },
  {
    id: 'toddler-20',
    title: 'Cognitive Education Learning Toy Preschool Early Learning Educational Toys for Children Toddlers Wooden Montessori Toys DF12266',
    category: 'montessori',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 4812.75,
    originalPrice: 5700,
    rating: 5.0,
    reviewsCount: 36,
    imageSrc: 'assets/products/extracted_1_2/img_20.jpg',
    imageType: 'wooden-blocks',
    material: 'Solid Natural Hardwood with Eco-Friendly Stain & Carrying Case',
    madeIn: 'Montessori Certified',
    inStock: true,
    tag: 'Cognitive Learning Kit',
    description: 'Montessori wooden cognitive learning gift kit with wooden case, ring stacker, color classification cylinders, cards, and object permanence drawer.',
    milestones: ['Object permanence', 'Size & color grading', 'Order and concentration']
  },
  {
    id: 'toddler-21',
    title: 'Oem Rts Baby Multifunction Low Prices 1st Walking Toys Factory Walker with Wheels ( pink and blue )',
    category: 'sensory',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y'],
    price: 3149.22,
    originalPrice: 3800,
    rating: 4.7,
    reviewsCount: 25,
    imageSrc: 'assets/products/extracted_1_2/img_21.jpg',
    imageType: 'wooden-walker',
    material: 'Reinforced BPA-Free PP Plastic with 360-Degree Swivel Wheels',
    madeIn: 'Safety Tested',
    inStock: true,
    tag: 'First Steps Walker',
    description: 'Lightweight multi-function baby walker with sturdy base, interactive activity play tray, and smooth caster wheels designed for supported upright walking practice.',
    milestones: ['Upright balance', 'Leg muscle strengthening', 'Directional steering']
  },
  {
    id: 'toddler-22',
    title: 'Wooden Kids Games Early Learning Baby Toys 1-3 Years Color Recognition Shape Matching Coin Toys',
    category: 'montessori',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 1645,
    originalPrice: 2100,
    rating: 4.9,
    reviewsCount: 41,
    imageSrc: 'assets/products/extracted_1_2/img_22.jpg',
    imageType: 'wooden-blocks',
    material: 'Solid Rubberwood with Water-based Color Lacquer',
    madeIn: 'Montessori Standard',
    inStock: true,
    tag: 'Coin Box & Shape Sorter',
    description: 'Montessori wooden color recognition shape matching drawer and coin insertion toy, promoting object permanence, pincer grasp, and color classification.',
    milestones: ['Wrist rotation', 'Slot alignment precision', 'Object permanence']
  },
  {
    id: 'toddler-23',
    title: '54-in-1 Montessori Busy Board English Spanish Sensory Toy Travel Outdoor Gift for 1+ Year Old Toddler',
    category: 'sensory',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 3701.26,
    originalPrice: 4400,
    rating: 5.0,
    reviewsCount: 58,
    imageSrc: 'assets/products/extracted_1_2/img_23.jpg',
    imageType: 'busy-board',
    material: 'High-Density Soft Felt Fabric with Secure Double-Stitched Fixtures',
    madeIn: 'Safety Certified',
    inStock: true,
    tag: '54-in-1 Travel Busy Bag',
    description: 'Deluxe 54-in-1 sensory busy board travel suitcase featuring bilingual English/Spanish alphabet cards, gears, clocks, buckles, and velcro shapes for travel entertainment.',
    milestones: ['Bilingual recognition', 'Fine motor coordination', 'Sensory tactile mastery']
  },
  {
    id: 'toddler-24',
    title: 'New Soft Silicone Geometric Rotating Toy - 360-degree Rotating Pop-up Leisure and Educational for Babies Aged 0-2 Years Old',
    category: 'sensory',
    secondaryCategory: 'newborn',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '0-1y'],
    price: 2200.75,
    originalPrice: 2750,
    rating: 4.8,
    reviewsCount: 37,
    imageSrc: 'assets/products/extracted_1_2/img_24.jpg',
    imageType: 'sensory-pop',
    material: '100% Food-Grade BPA-Free Soft Silicone',
    madeIn: 'Safety Certified',
    inStock: true,
    tag: 'Silicone Sensory Twist',
    description: 'BPA-free food-grade silicone geometric sensory rotating toy with 360-degree pop-up textures to soothe teething gums and strengthen bilateral hand twisting grip.',
    milestones: ['Grip strength', 'Bilateral wrist rotation', 'Oral sensory soothing']
  },
  {
    id: 'toddler-25',
    title: 'Wooden Baby Walker with Wheels and Activity Center Montessori Walking Toy for 1 Year Olds 20KG Load Capacity',
    category: 'wooden-local',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 10373.89,
    originalPrice: 12500,
    rating: 5.0,
    reviewsCount: 27,
    imageSrc: 'assets/products/extracted_1_2/img_25.jpg',
    imageType: 'wooden-walker',
    material: 'Heavy-Duty Solid Wood Construction with Silent Rubber Wheels',
    madeIn: 'Premium Handcrafted',
    inStock: true,
    tag: 'Heavy-Duty Wooden Bus Walker',
    description: 'High-capacity 20KG load wooden bus baby walker with speed-controlled wheels, internal toy storage trunk, and side bead activity center for steady walking guidance.',
    milestones: ['Supported independent steps', 'Trunk storage organization', 'Confidence & posture']
  },
  {
    id: 'toddler-26',
    title: '6 in 1 Montessori Wooden Activity Cube Educational Toys for Toddlers 1 to 3 Years Old Play for Boys and Girls',
    category: 'montessori',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 3705,
    originalPrice: 4500,
    rating: 4.9,
    reviewsCount: 49,
    imageSrc: 'assets/products/extracted_1_2/img_26.jpg',
    imageType: 'busy-board',
    material: 'Natural Hardwood Cube with Non-toxic Water-based Paint',
    madeIn: 'Montessori Certified',
    inStock: true,
    tag: '6-in-1 Wooden Cube',
    description: 'Solid wooden 6-in-1 activity cube featuring top bead maze, abacus, rotating alphabet number tiles, clock, shape sorter, and sliding animal maze.',
    milestones: ['Multi-dimensional problem solving', 'Clock & number logic', 'Spatial shape sorting']
  },
  {
    id: 'toddler-27',
    title: '6 in 1 Montessori Toy Set for Toddlers 1-3, Infant Teething Babies Toy Stacking Blocks Rings Pull String Toy Sorter Sensory Bin',
    category: 'sensory',
    secondaryCategory: 'montessori',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '0-1y', '2-3y'],
    price: 3890.21,
    originalPrice: 4650,
    rating: 4.9,
    reviewsCount: 63,
    imageSrc: 'assets/products/extracted_1_2/img_27.jpg',
    imageType: 'sensory-pop',
    material: 'Food-Grade Silicone, BPA-Free Textured Teethers & Elastic Cord Bin',
    madeIn: 'Safety Certified',
    inStock: true,
    tag: '6-in-1 Sensory Set',
    description: 'All-in-one toddler sensory development set with textured soft squeeze blocks, teething rings, sensory bin with elastic bands, and multi-texture pull-string UFO.',
    milestones: ['Elastic boundary exploration', 'Tactile texture differentiation', 'Pull-string motor grip']
  },
  {
    id: 'toddler-28',
    title: 'Multiple Hand Exercises Vibrant Color Matching Busy Board for Children',
    category: 'montessori',
    secondaryCategory: 'arts-fine-motor',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 2180,
    originalPrice: 2700,
    rating: 4.8,
    reviewsCount: 34,
    imageSrc: 'assets/products/extracted_1_2/img_28.jpg',
    imageType: 'busy-board',
    material: 'Natural Polish Wood Base with Rotating Color Plugs',
    madeIn: 'Montessori Standard',
    inStock: true,
    tag: 'Hand Exercise Busy Board',
    description: 'Vibrant color matching and twisting hand-exercise board designed to enhance finger dexterity, wrist rotation, and color pattern association.',
    milestones: ['Hand & finger strength', 'Color classification', 'Rotational motor skills']
  },
  {
    id: 'toddler-29',
    title: 'Baby Busy Board Train Montessori Sensory Toy Toddler Busy Board Montessori Toys for Toddler',
    category: 'sensory',
    secondaryCategory: 'wooden-local',
    ageRange: '1-2y',
    ageLabel: '1–2 Years',
    ageRanges: ['1-2y', '2-3y'],
    price: 3093.65,
    originalPrice: 3750,
    rating: 4.9,
    reviewsCount: 46,
    imageSrc: 'assets/products/extracted_1_2/img_29.jpg',
    imageType: 'wooden-train',
    material: 'Smooth Non-toxic ABS & Beechwood Rolling Carriage Connectors',
    madeIn: 'Child-Safe Certified',
    inStock: true,
    tag: 'Busy Board Train',
    description: 'Push-along sensory busy board train featuring rotating gears, animal shape sorters, spinning flower, and bead rollers for active crawling and walking toddlers.',
    milestones: ['Crawling & walking push motion', 'Cause-and-effect gear spins', 'Shape fitting']
  }
];

let content = fs.readFileSync('js/products.js', 'utf8');
const marker = 'export function getProductById(id)';
const splitIdx = content.indexOf(marker);
if (splitIdx === -1) throw new Error('Marker not found');

const lastBracket = content.lastIndexOf('}', splitIdx);
const before = content.substring(0, lastBracket + 1);
const after = content.substring(splitIdx);

const formattedItems = items.map(item => ',\n  ' + JSON.stringify(item, null, 4).replace(/\n/g, '\n  ')).join('');

const newContent = before + formattedItems + '\n];\n\n' + after;
fs.writeFileSync('js/products.js', newContent);
console.log('Successfully appended ' + items.length + ' toddler items to js/products.js!');
